### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [SamChou19815/SAM#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by SamChou19815** [comment]
Thanks for notifying me. Now I chose MIT License.
Check out the latest update:
https://github.com/SamChou19815/SAM/commit/8842a9a3f565479952616535a7f5ca71dcf379cd
